name: Feature request
description: Suggest an idea for this project
title: "[FEAT] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Welcome to `neuromaps`! Thanks for taking the time to suggest a new feature!
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: Tell us what feature you'd like to see
    validations:
      required: true
  - type: textarea
    id: problem-description
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of the original problem or challenge leading to this request.
      placeholder: Describe the problem that led to this feature request
    validations:
      required: false
  - type: textarea
    id: solution-description
    attributes:
      label: Describe a potential solution you have in mind (optional)
      description: A preliminary description of your expected solution.
      placeholder: Describe your expected solution
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional information (optional)
      description: Add any other context or references about the feature request here.
      placeholder: Any additional context, screenshots, or references
    validations:
      required: false
