"""For testing netneurotools.interface.freesurfer functionality."""

import numpy as np
import nibabel as nib
import pytest

from netneurotools.datasets import fetch_aparc, fetch_schaefer2018
from netneurotools.interface.freesurfer import extract_annot_labels
from netneurotools.interface.interface_utils import PARCIGNORE


@pytest.fixture(scope="session")
def prepare_annot_file(request, tmp_path_factory):
    """Prepare annotation file for FreeSurfer interface tests."""
    file_type = request.param["file_type"]
    version = request.param.get("version")
    data_dir = tmp_path_factory.mktemp("data")

    if file_type == "schaefer.annot":
        annot_file = fetch_schaefer2018(
            version="fsaverage5", data_dir=data_dir, verbose=0
        )["100Parcels7Networks"].L
    elif file_type == "aparc.annot":
        annot_file = fetch_aparc(version=version, data_dir=data_dir, verbose=0).L
    else:
        raise ValueError(f"Invalid file type: {file_type}")

    return annot_file


@pytest.mark.fetcher
@pytest.mark.parametrize(
    "prepare_annot_file",
    [
        {"file_type": "schaefer.annot", "version": "fsaverage5"},
        {"file_type": "aparc.annot", "version": "fsaverage"},
        {"file_type": "aparc.annot", "version": "fsaverage5"},
        {"file_type": "aparc.annot", "version": "fsaverage3"},
    ],
    ids=[
        "schaefer.annot",
        "aparc.annot-fsaverage",
        "aparc.annot-fsaverage5",
        "aparc.annot-fsaverage3",
    ],
    indirect=True,
)
def test_extract_annot_labels(prepare_annot_file):
    """Test extraction of keys and labels from annotation files."""
    annot_file = prepare_annot_file

    surf_data, keys, labels = extract_annot_labels(annot_file)
    assert isinstance(surf_data, np.ndarray)
    assert surf_data.ndim == 1
    assert isinstance(keys, tuple)
    assert isinstance(labels, tuple)
    assert len(keys) == len(labels)
    assert all(isinstance(k, int) for k in keys)
    assert all(isinstance(label, str) for label in labels)

    # Checking the keys were correctly generated by validating ignored labels
    # are not present in the keys
    _, _, annot_labels = nib.freesurfer.read_annot(annot_file)
    annot_labels = [label.decode() for label in annot_labels]
    assert not any(annot_labels[k] in PARCIGNORE for k in keys)
